version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: portfolio-backend
    ports:
      - "8081:8081"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8081
    depends_on:
      - backend
