version: '3.9'

services:
  backend:
    image: ghcr.io/harikeshverma03/portfolio-backend:latest
    container_name: portfolio-backend
    ports:
      - "8081:8081"
    restart: always

  frontend:
    image: ghcr.io/harikeshverma03/portfolio-frontend:latest
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8081
    depends_on:
      - backend
