name: Deploy to Raspberry Pi (via Cloudflare Access)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Write cloudflared credentials
      run: |
        mkdir -p ~/.cloudflared
        echo "{
          \"AccountTag\": \"\",
          \"TunnelID\": \"\",
          \"TunnelName\": \"\",
          \"Credentials\": {
            \"ClientID\": \"${{ secrets.CF_ACCESS_CLIENT_ID }}\",
            \"ClientSecret\": \"${{ secrets.CF_ACCESS_CLIENT_SECRET }}\"
          }
        }" > ~/.cloudflared/access.json

    - name: Proxy SSH with cloudflared
      run: |
        cloudflared access ssh --hostname ${{ secrets.SSH_HOST }} --id ${{ secrets.CF_ACCESS_CLIENT_ID }} --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }} &
        sleep 5

    - name: Deploy via SSH (tunneled)
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 2222" ./ ${{ secrets.SSH_USERNAME }}@localhost:/var/www/html/
