name: Build & Push to GHCR

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: harikeshverma03
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push backend (ARMv7)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/harikeshverma03/portfolio-backend:latest

      - name: Build and push frontend (ARMv7)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/harikeshverma03/portfolio-frontend:latest
